name: Build

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set-up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Decrypt JKS
      run: |
        echo "$JKS_STRING" | base64 --decode > app/infinity.p12

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    # Create APK Release
    - name: Build apk release project (APK)
      run: ./gradlew assembleRelease

    - name: Upload apk
      uses: actions/upload-artifact@v4
      with:
        name: Infinity-${{github.sha}}
        path: app/build/outputs/apk/
        if-no-files-found: error
